### PR TITLE
Streamwrapper: Fix bug in file mode validation method

### LINKED ISSUE #1552: In class-vip-filesystem-stream-wrapper.php#L755 `$stats` seems to be undefined
In https://github.com/Automattic/vip-go-mu-plugins/blob/master/files/class-vip-filesystem-stream-wrapper.php#L755 `$stats` seems to be undefined

### PR DESCRIPTION
**Pull request by hanifn**
## Description

A bug in the file mode validation method results in it returning an undefined value instead of true.

Fixes #1552  

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).

## Steps to Test

Example:

1. Check out PR.
1. Upload code to sandbox
1. `wp shell`
1. Create a new file with mode `x`: `fopen( 'vip://wp-content/uploads/new-file.txt', 'x' );`
1. Verify file opened properly

### CODE REVIEW

**Comment by mjangda** [comment]
> is the errors array on the test class reset for each test?

Doesn't look like it. We should reset it in `tearDown()`.

File: tests/files/test-vip-filesystem-stream-wrapper.php [hunk 1]
```diff
@@ -2,11 +2,15 @@
...
 namespace Automattic\VIP\Files;
 
+use \WP_Error;
+
 class VIP_Filesystem_Stream_Wrapper_Test extends \WP_UnitTestCase {
 	private $stream_wrapper;
 
 	private $api_client_mock;
 
+	private $errors;
```
Comment (mjangda) [inline tests/files/test-vip-filesystem-stream-wrapper.php:12]:
```suggestion
	private $errors = [];
```

File: tests/files/test-vip-filesystem-stream-wrapper.php [hunk 2]
```diff
@@ -19,12 +23,16 @@ public function setUp() {
...
 		$this->stream_wrapper = new VIP_Filesystem_Stream_Wrapper( $this->api_client_mock ); 
+
+		set_error_handler( [ $this, 'errorHandler' ] );
 	}
 
 	public function tearDown() {
 		$this->stream_wrapper = null;
 		$this->api_client_mock = null;
 
+		restore_error_handler();
```
Comment (mjangda) [inline tests/files/test-vip-filesystem-stream-wrapper.php:34]:
```suggestion
		$this->errors = [];

		restore_error_handler();
```

**Comment by mjangda** [comment]
r883-stacks
