### PR TITLE
test: address `http_api_transports` deprecation in WP 6.4

### LINKED ISSUE #4902: Hook http_api_transports is deprecated since version 6.4.0 with no alternative available
> 1) Automattic\VIP\Files\Curl_Streamer_Test::test__init
> Unexpected deprecation notice for http_api_transports.
> Hook http_api_transports is deprecated since version 6.4.0 with no alternative available. 
> Failed asserting that an array is empty.
> 
> /tmp/wordpress-tests-lib/includes/abstract-testcase.php:638
> /tmp/wordpress-tests-lib/includes/abstract-testcase.php:650
> /home/runner/work/vip-go-mu-plugins/vip-go-mu-plugins/vendor/yoast/phpunit-polyfills/src/TestCases/TestCasePHPUnitGte8.php:84

Ref: https://github.com/Automattic/vip-go-mu-plugins/actions/runs/6319951465/job/17161735106?pr=4901#step:5:313

### PR DESCRIPTION
**Pull request by sjinks**
Fixes: #4902

### CODE REVIEW

File: tests/files/test-curl-streamer.php [hunk 1]
```diff
@@ -31,6 +31,13 @@ public function tearDown(): void {
 	}
 
 	public function test__init() {
+		global $wp_version;
+
+		$version = preg_replace( '/-.*$/', '', $wp_version );
+		if ( version_compare( $version, '6.4', '>=' ) ) {
+			$this->setExpectedDeprecated( 'http_api_transports' );
+		}
```
Comment (sjinks) [inline tests/files/test-curl-streamer.php:39]: Right now, there is no other way around this deprecation. WordPress calls `_get_first_available_transport()` from `wp_http_supports()` invoking this deprecated filter.

**Review by rebeccahum — APPROVED** [review]
