### PR TITLE
GH-2980: make sure `wpcom_vip_override_role_caps()` persists capabilities

### LINKED ISSUE #2980: Function wpcom_vip_override_role_caps doesn't work as expected
## Expected/Desired Behavior

Given a role, the function ``wpcom_vip_override_role_caps`` is expected to override the role's current capabilities by the one(s) sent as a parameter. 

## Actual Behavior

The role capabilities remain unchanged. 

## Steps to Reproduce the Problem

1. Via WP Shell: execute the function. sending the role to be modified and the caps to be applied;
In the code below, I'm using as an example the role `contributor` and the capability ``read``.

```
wp> wpcom_vip_override_role_caps( 'contributor', array( 'read' => false ) );
```

2. Via WP CLI: Check whether the capabilities for the role 'contributor' have changed.

```
~# wp cap list "contributor"
	my-custom-cap
	edit_posts
	read
	level_1
	level_0
```

The capabilities remain the same while it should be empty. 

## Additional notes

**Code:**  https://github.com/Automattic/vip-go-mu-plugins/blob/master/vip-helpers/vip-roles.php#L82-L92
**VIP how to customize user roles public docs:** https://docs.wpvip.com/how-tos/customize-user-roles/

### PR DESCRIPTION
**Pull request by sjinks**
## Description

This PR fixes #2980 by adding the code to persist the overridden capabilities to the database.

### Plugin Updated: VIP Helpers

Bug fix: `wpcom_vip_override_role_caps()` now persists the capabilities to the database.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

The CI should pass -- I have added a test case for this issue.

### CODE REVIEW

File: vip-helpers/vip-roles.php [hunk 1]
```diff
@@ -88,6 +88,11 @@ function wpcom_vip_override_role_caps( $role, $caps ) {
 
 	$role_obj->capabilities = (array) $caps;
 
+	$roles = wp_roles();
+
+	$roles->roles[ $role ]['capabilities'] = $caps;
+	update_option( $roles->role_key, $roles->roles );
```
Comment (sjinks) [inline vip-helpers/vip-roles.php:94]: There was an option to use `remove_cap()` and `add_cap()` in a loop instead; however, I did not like that because it would trigger `update_option()` for every operation, and that does not look database- and cache-friendly.
_

**Comment by sjinks** [comment]
r2433-stacks

**Comment by sjinks** [comment]
v20220413.0
