### PR TITLE
fix: PHP 8.4 compatibility

### LINKED ISSUE #6491: PHP 8.4 Support
I would like to see PHP 8.4 testing added to CI on this repository, as well as the issues within this repository fixed. For example, https://github.com/Automattic/vip-go-mu-plugins/blob/develop/telemetry/tracks/class-tracks-client.php#L34 throws an error because of https://wiki.php.net/rfc/deprecate-implicitly-nullable-types.

Is this planned for the near future?

## Full Log of Errors

```
PHP Deprecated:  Constant E_STRICT is deprecated in /tmp/wordpress/wp-content/mu-plugins/lib/wpcom-error-handler/wpcom-error-handler.php on line 134
Deprecated: Automattic\VIP\Telemetry\Tracks::__construct(): Implicitly marking parameter $queue as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/telemetry/tracks/class-tracks.php on line 48 [example.org] [wp-content/mu-plugins/000-vip-init.php:241 require_once('wp-content/mu-plugins/lib/wpcom-error-handler/wpcom-error-handler.php'), wp-settings.php:456 include_once('wp-content/mu-plugins/000-vip-init.php'), wp-content/plugins/mantle-framework/src/mantle/testing/wordpress-bootstrap.php:239 require_once('wp-settings.php'), wp-content/plugins/mantle-framework/src/mantle/testing/install-wordpress.php:43 require_once('wp-content/plugins/mantle-framework/src/mantle/testing/wordpress-bootstrap.php')]
PHP Deprecated:  Constant E_STRICT is deprecated in /tmp/wordpress/wp-content/mu-plugins/lib/wpcom-error-handler/wpcom-error-handler.php on line 134
Deprecated: Automattic\VIP\Telemetry\Tracks\Tracks_Client::__construct(): Implicitly marking parameter $http as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/telemetry/tracks/class-tracks-client.php on line 34 [example.org] [wp-content/mu-plugins/000-vip-init.php:244 require_once('wp-content/mu-plugins/lib/wpcom-error-handler/wpcom-error-handler.php'), wp-settings.php:456 include_once('wp-content/mu-plugins/000-vip-init.php'), wp-content/plugins/mantle-framework/src/mantle/testing/wordpress-bootstrap.php:239 require_once('wp-settings.php'), wp-content/plugins/mantle-framework/src/mantle/testing/install-wordpress.php:43 require_once('wp-content/plugins/mantle-framework/src/mantle/testing/wordpress-bootstrap.php')]
PHP Deprecated:  Constant E_STRICT is deprecated in /tmp/wordpress/wp-content/mu-plugins/lib/wpcom-error-handler/wpcom-error-handler.php on line 134
Deprecated: Automattic\VIP\Files\Meta_Updater::__construct(): Implicitly marking parameter $log_file as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/files/class-meta-updater.php on line 39 [example.org] [wp-content/mu-plugins/a8c-files.php:42 require_once('wp-content/mu-plugins/lib/wpcom-error-handler/wpcom-error-handler.php'), wp-settings.php:456 include_once('wp-content/mu-plugins/a8c-files.php'), wp-content/plugins/mantle-framework/src/mantle/testing/wordpress-bootstrap.php:239 require_once('wp-settings.php'), wp-content/plugins/mantle-framework/src/mantle/testing/install-wordpress.php:43 require_once('wp-content/plugins/mantle-framework/src/mantle/testing/wordpress-bootstrap.php')]
PHP Deprecated:  Constant E_STRICT is deprecated in /tmp/wordpress/wp-content/mu-plugins/lib/wpcom-error-handler/wpcom-error-handler.php on line 134
Deprecated: Automattic\VIP\Admin_Notice\WP_Version_Condition::__construct(): Implicitly marking parameter $maximum_version as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/admin-notice/conditions/class-wp-version-condition.php on line 17 [example.org] [wp-content/mu-plugins/admin-notice/admin-notice.php:15 require_once('wp-content/mu-plugins/lib/wpcom-error-handler/wpcom-error-handler.php'), wp-content/mu-plugins/admin-notice.php:12 require_once('wp-content/mu-plugins/admin-notice/admin-notice.php'), wp-settings.php:456 include_once('wp-content/mu-plugins/admin-notice.php'), wp-content/plugins/mantle-framework/src/mantle/testing/wordpress-bootstrap.php:239 require_once('wp-settings.php'), wp-content/plugins/mantle-framework/src/mantle/testing/install-wordpress.php:43 require_once('wp-content/plugins/mantle-framework/src/mantle/testing/wordpress-bootstrap.php')]

PHP Deprecated:  Automattic\VIP\Telemetry\Tracks::__construct(): Implicitly marking parameter $queue as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/telemetry/tracks/class-tracks.php on line 48

Deprecated: Automattic\VIP\Telemetry\Tracks::__construct(): Implicitly marking parameter $queue as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/telemetry/tracks/class-tracks.php on line 48
PHP Deprecated:  Automattic\VIP\Telemetry\Tracks\Tracks_Client::__construct(): Implicitly marking parameter $http as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/telemetry/tracks/class-tracks-client.php on line 34

Deprecated: Automattic\VIP\Telemetry\Tracks\Tracks_Client::__construct(): Implicitly marking parameter $http as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/telemetry/tracks/class-tracks-client.php on line 34
PHP Deprecated:  Automattic\VIP\Files\Meta_Updater::__construct(): Implicitly marking parameter $log_file as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/files/class-meta-updater.php on line 39

Deprecated: Automattic\VIP\Files\Meta_Updater::__construct(): Implicitly marking parameter $log_file as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/files/class-meta-updater.php on line 39
PHP Deprecated:  Automattic\VIP\Admin_Notice\WP_Version_Condition::__construct(): Implicitly marking parameter $maximum_version as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/admin-notice/conditions/class-wp-version-condition.php on line 17

Deprecated: Automattic\VIP\Admin_Notice\WP_Version_Condition::__construct(): Implicitly marking parameter $maximum_version as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/admin-notice/conditions/class-wp-version-condition.php on line 17
PHP Deprecated:  Automattic\VIP\Jetpack\Connection_Pilot::should_attempt_reconnection(): Implicitly marking parameter $error as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php on line 284

Deprecated: Automattic\VIP\Jetpack\Connection_Pilot::should_attempt_reconnection(): Implicitly marking parameter $error as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php on line 284
PHP Deprecated:  Prometheus\CollectorRegistry::registerHistogram(): Implicitly marking parameter $buckets as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/CollectorRegistry.php on line 219
PHP Deprecated:  Prometheus\CollectorRegistry::getOrRegisterHistogram(): Implicitly marking parameter $buckets as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/CollectorRegistry.php on line 267
PHP Deprecated:  Prometheus\CollectorRegistry::registerSummary(): Implicitly marking parameter $quantiles as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/CollectorRegistry.php on line 294
PHP Deprecated:  Prometheus\CollectorRegistry::getOrRegisterSummary(): Implicitly marking parameter $quantiles as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/CollectorRegistry.php on line 345

Deprecated: Prometheus\CollectorRegistry::registerHistogram(): Implicitly marking parameter $buckets as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/CollectorRegistry.php on line 219

Deprecated: Prometheus\CollectorRegistry::getOrRegisterHistogram(): Implicitly marking parameter $buckets as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/CollectorRegistry.php on line 267

Deprecated: Prometheus\CollectorRegistry::registerSummary(): Implicitly marking parameter $quantiles as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/CollectorRegistry.php on line 294

Deprecated: Prometheus\CollectorRegistry::getOrRegisterSummary(): Implicitly marking parameter $quantiles as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/CollectorRegistry.php on line 345
PHP Deprecated:  Prometheus\RegistryInterface::registerHistogram(): Implicitly marking parameter $buckets as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/RegistryInterface.php on line 94
PHP Deprecated:  Prometheus\RegistryInterface::getOrRegisterHistogram(): Implicitly marking parameter $buckets as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/RegistryInterface.php on line 121
PHP Deprecated:  Prometheus\RegistryInterface::registerSummary(): Implicitly marking parameter $quantiles as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/RegistryInterface.php on line 134
PHP Deprecated:  Prometheus\RegistryInterface::getOrRegisterSummary(): Implicitly marking parameter $quantiles as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/RegistryInterface.php on line 163

Deprecated: Prometheus\RegistryInterface::registerHistogram(): Implicitly marking parameter $buckets as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/RegistryInterface.php on line 94

Deprecated: Prometheus\RegistryInterface::getOrRegisterHistogram(): Implicitly marking parameter $buckets as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/RegistryInterface.php on line 121

Deprecated: Prometheus\RegistryInterface::registerSummary(): Implicitly marking parameter $quantiles as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/RegistryInterface.php on line 134

Deprecated: Prometheus\RegistryInterface::getOrRegisterSummary(): Implicitly marking parameter $quantiles as nullable is deprecated, the explicit nullable type must be used instead in /tmp/wordpress/wp-content/mu-plugins/prometheus/vendor/promphp/prometheus_client_php/src/Prometheus/RegistryInterface.php on line 163
```

### PR DESCRIPTION
**Pull request by sjinks**
## Description

This pull request focuses on improving type safety and compatibility with newer PHP and WordPress versions, along with some minor code cleanups. The most important changes are grouped below:

### PHP type safety and constructor improvements

* Updated several constructors to use nullable type hints (`?type`) for parameters that can be `null`, improving type safety and clarity in classes such as `WP_Version_Condition`, `Meta_Updater`, `Tracks_Client`, `Tracks`, and a private method in `Jetpack_Connection_Pilot`. [[1]](diffhunk://#diff-47567c4a43f806fb3e8153e06adc83300f16209feb2ab958ae9233b7255580deL13-R17) [[2]](diffhunk://#diff-14b5e362fc86712a5c9dacdb218e2bb7c811c30c707e2bd7c32d4cf725cf6a27L39-R39) [[3]](diffhunk://#diff-c56cb65343d466e78c304485ae4c62c57be87dacf9f8f0353155f2de95bc2d62L34-R34) [[4]](diffhunk://#diff-19a3f8db9b6d637dbb07d4dbfb2eaaf0635239753371034e6e14c5b4aa78260dL48-R48) [[5]](diffhunk://#diff-2e8afd16cc8ce020a84de51d55e31b1d1e79d096ec093ea17ed73de79f2ddeedL284-R284)

### PHP and WordPress compatibility

* Updated the PHPCompatibility sniff configuration to test against PHP 8.1+ and raised the minimum supported WordPress version to 6.2 in `phpcs.xml.dist`.
* Adjusted error handling for `E_STRICT` to account for its deprecation in PHP 8.4, moving the handling behind a version check and removing its case from the main error handler switch. [[1]](diffhunk://#diff-a0969fa2ee65c09e3d9eb6cf81f817c160d427e0e98608ba934bb0fbd817f9a3L134-L136) [[2]](diffhunk://#diff-a0969fa2ee65c09e3d9eb6cf81f817c160d427e0e98608ba934bb0fbd817f9a3R146-R150)

### Minor code cleanup

* Removed an unused parameter from the `register_qm_collector_environment` function and updated the corresponding filter registration in the Query Monitor environment collector.

Fixes: #6491

### Fixed
- PHP 8.4 compatibility issues

## Pre-review checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally or in Codespaces (or has an appropriate fallback).
- [ ] This change works and has been tested on a sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Pre-deploy checklist

- [ ] VIP staff: Ensure any alerts added/updated conform to internal standards (see internal documentation). 

## Steps to Test

CI must pass.

### CODE REVIEW

**Review by rinatkhaziev — APPROVED** [review]

File: query-monitor/collectors/environment.php [hunk 1]
```diff
@@ -330,12 +330,11 @@ protected static function get_current_user() {
...
  * @return array<string, QM_Collector>
  */
-function register_qm_collector_environment( array $collectors, QueryMonitor $qm ) {
+function register_qm_collector_environment( array $collectors ) {
 	$collectors['environment'] = new QM_Collector_Environment();
 	return $collectors;
 }
 
-add_filter( 'qm/collectors', 'register_qm_collector_environment', 20, 2 );
+add_filter( 'qm/collectors', 'register_qm_collector_environment', 20 );
```
Comment (rinatkhaziev) [inline query-monitor/collectors/environment.php:340]: This probably needs to be raised upstream?

**Review by rinatkhaziev — COMMENTED** [review]
I've approved but this QM left me wondering
