### PR TITLE
Change set_group_for_user() to check if group is registered first

### LINKED ISSUE #1147: Vary Cache: Trigger warning for set_group_for_user if not group not registered
If I call `set_group_for_user` without having registered the group first (via `register_groups`), the current request will send correct Vary headers but others will not. This can be problematic and lead to unexpected behaviour.

We should add a check to `set_group_for_user` to make sure that the `group` exists before proceeding.

### PR DESCRIPTION
**Pull request by dchymko**
## Description

We need to check to make sure that he group has been added via register_groups() before try adding the user to it.

Fixes #1147 

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).

## Steps to Test

Outline the steps to test and verify the PR here.

Example:

1. Check out PR.
2. Callng `var_dump(Vary_Cache::set_group_for_user( 'dev-group', 'yay' ) );` should output an error
3. Adding `Vary_Cache:register_group('dev-group');` before that line should output true

### CODE REVIEW

File: cache/class-vary-cache.php [hunk 1]
```diff
@@ -229,12 +229,16 @@ public static function set_group_for_user( $group, $value ) {
 
 		$validate_group_result = self::validate_cookie_value( $group );
 		if ( is_wp_error( $validate_group_result ) ) {
-			return new WP_Error( 'invalid_vary_group_name', sprintf( 'Failed to register group (%s): %s', $group, $validate_group_result->get_error_message() ) );
+			return new WP_Error( 'invalid_vary_group_name', sprintf( 'Failed to set group (%s): %s', $group, $validate_group_result->get_error_message() ) );
```
Comment (mjangda) [inline cache/class-vary-cache.php]: Good catch :)

**Comment by dchymko** [comment]
r132389-deploy
