### PR TITLE
Fixes warning while reading integration config for PHP 8+

### LINKED ISSUE #4878: `file_get_contents()` repeatedly called on not existing file
## Expected/Desired Behavior

`file_get_contents` at [this](https://github.com/Automattic/vip-go-mu-plugins/blob/9cea8f3ed04e0130f1470013745ef600fb8d08b4/integrations/integration-vip-config.php#L92) line should stop to produce Warnings if the file checked doesn't exist (whatever PHP version is being used).

## Actual Behavior

Right now, that line produces a warning in PHP 8+ if the file doesn't exists. This is probably caused by the fact the the Error Control Operator (`@`) changed its behavior from PHP 8.

Specifically the errors are triggered for both Parsely and Block Data Api integrations:

`file_get_contents(/var/www/config/integrations-config/parsely-config.php): Failed to open stream: No such file or directory`
`file_get_contents(/var/www/config/integrations-config/block-data-api-config.php): Failed to open stream: No such file or directory`

## Steps to Reproduce the Problem

Just loading any page in an environment where Warnings are visible should be enough (Probably also having the integrations disabled is required?).

## Additional notes

Is invalidating the cache of the config file before checking for its existence a doable solution for you? This way `file_get_content` can be just avoided.

Otherwise is there any chance to not reach that part of code at all if the integrations are not active? So the part would be just skipped for whose are not supposed to use it.

### PR DESCRIPTION
**Pull request by mehmoodak**
## Description

In VIP Integrations we used `@file_get_contents` to read config file of each integration. We expected that `@` will suppress all warnings but for PHP 8+ it is still producing a warning if file doesn't exist.

Closes: https://github.com/Automattic/vip-go-mu-plugins/issues/4878

## Changelog Description

Fixes warning while reading integration config file for PHP 8+

## Pre-review checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Pre-deploy checklist

- [ ] VIP staff: Ensure any alerts added/updated conform to internal standards (see internal documentation). 

## Steps to Test

1. Check out PR.
1. If needed setup new environment via `vip dev-env create`
1. Open dev site on browser
1. Use `vip dev-env logs --slug vip-single-site -S php -d -f` to verify that no warning is generated while reloading or navigating dev site.

### CODE REVIEW

File: integrations/integration-vip-config.php [hunk 1]
```diff
@@ -82,20 +82,31 @@ protected function get_vip_config_from_file( string $slug ) {
...
+
 		/**
 		 * Clear cache to always read data from latest config file.
 		 *
 		 * Kubernetes ConfigMap updates the file via symlink instead of actually replacing the file and
 		 * PHP cache can hold a reference to the old symlink that can cause fatal if we use require
 		 * on it.
 		 */
-		if ( false === @file_get_contents( $config_file_path ) ) { // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
+		if ( false === file_get_contents( $config_file_path ) ) {
```
Comment (mehmoodak) [inline integrations/integration-vip-config.php]: Another solution is to avoid this `if` statement and always read latest config from file.

Personally I am more inclined toward this solution because its simpler and always reading simple configs from file doesn't seems like an expensive operation.

Please do let me know about your thoughts on this solution.

**Review by sjinks — APPROVED** [review]

File: integrations/integration-vip-config.php (hunk 1 above)
Comment (mjangda) [reply integrations/integration-vip-config.php]: > always read latest config from file

Do you mean just running `clearstatcache` and then `require`? If so, we should do a quick benchmark to see the impact before doing this.

Comment (mehmoodak) [reply integrations/integration-vip-config.php]: Did some quick benchmarking on local machine and here are the stats:

1. `clearstatcache()` with disable warning and if statement is on average taking 2.5 * E-4 seconds
1. `clearstatcache()` without if statement is on average taking 4.0 * E-5 seconds 


```php
$start_time = microtime(true);

// Code here

$end_time = microtime(true);
$execution_time = $end_time - $start_time;

echo "Execution Time: {$execution_time} seconds";
```

Based on these benchmarks removing the if statement and making the code simpler.
