### PR TITLE
Fix confusing code comment

### LINKED ISSUE #757: WPCOM_IS_VIP_ENV defined as false; comments indicate it's defined as true
In `000-vip-init.php`, WPCOM_IS_VIP_ENV defined as false; comments indicate it's defined as true:

```
// For backwards compatibility - always true.
if ( ! defined( 'WPCOM_IS_VIP_ENV' ) ) {
	define( 'WPCOM_IS_VIP_ENV', false );
}
```

I would expect the comment to reflect the actual value.

### PR DESCRIPTION
**Pull request by joshbetz**
Fixes #757

props @simonwheatley | h/t @paulschrieber

### CODE REVIEW

File: 000-vip-init.php [hunk 1]
```diff
@@ -27,7 +27,7 @@
 	define( 'VIP_GO_ENV', false );
 }
 
-// For backwards compatibility - always true.
+// For backwards compatibility - always true on a VIP Go environment.
```
Comment (mjangda) [inline 000-vip-init.php]: The constant is pretty heavily used so I think we should probably remove the part about back compat.

**Comment by mjangda** [comment]
r99375-deploy
